name: auto commit

on:
  schedule:
  - cron: "0 9,16 * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Commit
        run: |
          git config --global user.name "${GITHUB_REPOSITORY_OWNER}"
          git config --global user.email "${GITHUB_REPOSITORY_OWNER}@users.noreply.github.com"
          git commit --allow-empty -m "auto commit: `date "+%Y-%m-%d %H:%M:%S"`"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
